set nocompatible
syntax on

" Enable line numbers
set number

" Make tabs as wide as two spaces
set tabstop=4
set shiftwidth=4
set expandtab

" Show invisible characters
set lcs=tab:▸\ ,trail:·,eol:¬,nbsp:_
set list

" spell check my git commits
autocmd FileType gitcommit setlocal spell

