# brew tap homebrew/bundle
# brew bundle

cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'

brew 'ack'
brew 'bash-completion'
brew 'coreutils'
brew 'git'
brew 'gnupg'
brew 'gpg'
brew 'htop'
brew 'hub'
brew 'jpeg'
brew 'jq'
brew 'openssl'
brew 'pinentry-mac'
brew 'readline'
brew 'tig'
brew 'wget'

cask 'alfred'
cask 'docker'
cask 'flux'
cask 'fork'
cask 'gimp'
cask 'iterm2'
cask 'jetbrains-toolbox'
cask 'keybase'
cask 'sublime-text'
cask 'visual-studio-code'
cask 'vlc'
cask 'postman'
cask 'plex-media-player'
