#!/usr/bin/env bash
#
# removes all of the branches that are already merged into master

branch_name=$(git branch-name)
if [[ "$branch_name" == "master" ]]; then
    git branch --merged | grep -v "\*" | xargs -n 1 git branch -d
    echo "Done!"
else
    echo "Must be on master, not $branch_name!"
fi
