#!/usr/bin/env bash
#
# Pushes the current branch to the origin remote and sets upstream tracking.

branch_name=$(git branch-name)
if [[ "$branch_name" == "master" ]]; then
    echo "You are on master!"
else
    git push --set-upstream origin ${branch_name}
fi
