#!/usr/bin/env bash

export PATH="$PATH:/usr/local/heroku/bin:/usr/local/jetbrains/bin"
export VAGRANT_DEFAULT_PROVIDER=vmware_fusion

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
