#!/usr/bin/env bash

gifify() {
  if [[ -n "$1" ]]; then
    if [[ $2 == '--good' ]]; then
      ffmpeg -i $1 -r 10 -vcodec png out-static-%05d.png
      time convert -verbose +dither -layers Optimize -resize 600x600\> out-static*.png  GIF:- | gifsicle --colors 128 --delay=5 --loop --optimize=3 --multifile - > $1.gif
      rm out-static*.png
    else
      ffmpeg -i $1 -s 600x400 -pix_fmt rgb24 -r 10 -f gif - | gifsicle --optimize=3 --delay=3 > $1.gif
    fi
  else
    echo "proper usage: gifify <input_movie.mov> [--good]. You DO need to include extension."
  fi
}

docker-destroy-all(){
  # Stop all containers
  containers=`docker ps -a -q`
  if [ -n "$containers" ] ; then
    docker stop $containers
  fi

  # Delete all containers
  containers=`docker ps -a -q`
  if [ -n "$containers" ]; then
    docker rm -f -v $containers
  fi

  # Delete all images
  images=`docker images -q -a`
  if [ -n "$images" ]; then
    docker rmi -f $images
  fi
}

# https://stackoverflow.com/a/30029855/823942
listening() {
    if [ $# -eq 0 ]; then
        sudo lsof -iTCP -sTCP:LISTEN -n -P
    elif [ $# -eq 1 ]; then
        sudo lsof -iTCP -sTCP:LISTEN -n -P | grep -i --color $1
    else
        echo "Usage: listening [pattern]"
    fi
}
